taiga-family/editor

.github/actions/cleanup-cache/action.yml, .github/workflows/auto-add-to-project.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-rebase.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-deps-renovate.yml, .github/workflows/build-demo.yml, .github/workflows/build.yml, default.json
=> ci: add workflows

apps/demo-integrations/cypress/tests/editor-anchor.cy.ts, apps/demo/src/app/app.component.ts, apps/demo/src/app/app.style.less, apps/demo/src/styles.less
=> ci: cypress

.github/workflows/auto-merge.yml
=> chore: check auto merge

renovate.json
=> chore: trigger

.github/workflows/auto-update-deps-renovate.yml, package-lock.json, package.json, renovate.json
=> chore: trigger for renovate

.github/actions/variables/action.yml
=> chore: update

.devcontainer/devcontainer.json
=> ci: support github codespaces

.devcontainer/devcontainer.json
=> ci: change machine type

.github/workflows/auto-approve.yml, .npmrc, package-lock.json, package.json
=> chore: trigger renovate

.github/workflows/auto-approve.yml
=> chore: revert

apps/demo/src/app/pages/color-picker/examples/4/index.less, libs/tui-editor/components/input-color/input-color.style.less
=> fix: show cursor `pointer` for color `picker`

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-update-deps-renovate.yml, .github/workflows/release.yml, .github/workflows/snapshots.yml, README.md
=> docs: update REAMDE.md

.github/workflows/auto-cleanup-caches.yml
=> chore: fixup

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/build-demo.yml, .github/workflows/build.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml
=> ci: use pretty path to actions

renovate.json
=> chore: refactor renovate.json

.github/workflows/deploy-preview.yml, apps/demo/project.json, firebase.json
=> chore: change dist

.github/workflows/deploy.yml
=> chore: fix deploy dist

libs/tui-editor/components/editor-socket/styles/list.less
=> feat: change margin for list

libs/tui-editor/components/editor-socket/editor-socket.component.ts
=> fix: expect null pointer

libs/tui-editor/components/editor/editor.module.ts
=> fix: can't resolve item.directive.ts, but not a .d.ts file

.github/workflows/auto-cleanup-caches.yml
=> ci: cleanup cache

apps/demo/src/app/pages/stackblitz/project-files/src/app/app.module.ts.md
1. Open https://taiga-family.github.io/tui-editor/stackblitz
2. Click "Font color" tool
=> chore(demo): add `BrowserAnimationsModule` to Stackblitz starter

apps/demo/src/app/pages/starter/editor-starter.template.html
=> chore: fix

libs/tui-editor/components/color-selector/color-edit/color-edit.style.less, libs/tui-editor/components/color-selector/color-edit/color-edit.template.html
=> feat: improve ui for color-edit component

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-sync-submodule.yml, .github/workflows/build-demo.yml, .github/workflows/build.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml
=> ci: decompose

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-sync-submodule.yml, .github/workflows/build-demo.yml, .github/workflows/build.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, package-lock.json
=> ci: upgrade

.github/workflows/auto-wait-successful.yml, .github/workflows/e2e.yml
=> ci: add auto wait

.github/workflows/auto-wait-successful.yml
=> ci: approve on success

projects/tui-editor/extensions/link/link.ts
=> feat: support copy paste multiple links

package-lock.json, projects/demo/src/app/app.routes.ts
=> chore: refactor

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-sync-submodule.yml, .github/workflows/build-demo.yml, .github/workflows/build.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, package-lock.json, package.json, projects/tui-editor/components/color-selector/color-edit/color-edit.module.ts, projects/tui-editor/components/color-selector/color-edit/color-edit.template.html
=> feat: remove `tui-input-count`

projects/tui-editor/extensions/image-editor/image-editor.extension.ts
=> fix: use image loader when using drag-and-drop images

.github/workflows/snapshots.yml
=> chore: add snapshot

.github/workflows/snapshots.yml, projects/demo-cypress/cypress/support/helpers/visit.ts, projects/demo-cypress/cypress/tests/editor-color-picker.cy.ts, projects/demo/src/app/pages/anchors/examples/1/index.ts, projects/demo/src/app/pages/custom-tool/paste-image/examples/1/index.ts, projects/demo/src/app/pages/embed/html5/examples/1/index.ts, projects/demo/src/app/pages/embed/iframe/examples/1/index.ts, projects/demo/src/app/pages/focus/examples/1/index.ts, projects/demo/src/app/pages/images/preview/examples/1/index.ts, projects/demo/src/app/pages/images/resizable/examples/1/index.ts, projects/demo/src/app/pages/images/upload/examples/1/index.ts, projects/demo/src/app/pages/starter/editor-starter.component.ts, projects/demo/src/app/pages/starter/import/import-module.md, projects/tui-editor/components/editor-resizable/editor-resizable.abstract.ts, projects/tui-editor/constants/default-editor-tools.ts, projects/tui-editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/tui-editor/extensions/default-editor-extensions/default-editor-extensions.ts, projects/tui-editor/extensions/iframe-editor/iframe-editor.component.ts, projects/tui-editor/extensions/image-editor/image-editor.component.ts, projects/tui-editor/extensions/starter-kit/starter-kit.ts, projects/tui-editor/extensions/tiptap-node-view/node-view-render.ts
=> fix: undo operation should work when updating attributes

projects/tui-editor/src/components/editor/editor.component.less
=> fix: strange behaviour on Windows

projects/demo/src/app/pages/starter/editor-starter.template.html, projects/tui-editor/components/editor-socket/editor-socket.component.ts, projects/tui-editor/components/editor/editor.component.html, projects/tui-editor/tokens/editor-options.ts
=> feat: add `enableDefaultStyles` option

lerna.json, package.json, projects/tui-editor/components/editor/editor.component.less
=> fix: change hidden to clip

.github/workflows/release.yml, .github/workflows/snapshots.yml, package.json
=> chore: fix ci

projects/demo/src/app/app.pages.ts, projects/demo/src/app/app.routes.ts, projects/demo/src/app/constants/demo-path.ts, projects/demo/src/app/pages/color-picker/examples/1/index.ts, projects/demo/src/app/pages/starter/index.html, projects/demo/src/app/pages/starter/index.ts, projects/demo/src/app/pages/toolbar/floating/examples/1/index.html, projects/demo/src/app/pages/toolbar/floating/examples/1/index.less, projects/demo/src/app/pages/toolbar/floating/examples/1/index.ts, projects/demo/src/app/pages/toolbar/floating/index.html, projects/demo/src/app/pages/toolbar/floating/index.ts, projects/tui-editor/src/components/editor/dropdown/dropdown-toolbar.directive.ts, projects/tui-editor/src/components/editor/editor.component.html, projects/tui-editor/src/components/editor/editor.component.less, projects/tui-editor/src/components/editor/editor.component.ts, projects/tui-editor/src/constants/default-editor-colors.ts, projects/tui-editor/src/index.ts, projects/tui-editor/src/tokens/editor-options.ts
=> feat: add floating toolbar

package-lock.json, projects/demo/src/app/app.pages.ts, projects/demo/src/app/app.routes.ts, projects/demo/src/app/constants/demo-path.ts, projects/demo/src/app/pages/checkbox/editor-checkbox.component.html, projects/demo/src/app/pages/checkbox/editor-checkbox.component.ts, projects/demo/src/app/pages/checkbox/editor-checkbox.module.ts, projects/demo/src/app/pages/checkbox/examples/1/index.html, projects/demo/src/app/pages/checkbox/examples/1/index.ts, projects/tui-editor/abstract/editor-adapter.abstract.ts, projects/tui-editor/components/editor-socket/editor-socket.component.less, projects/tui-editor/components/editor-socket/styles/checkbox.less, projects/tui-editor/components/editor-socket/styles/list.less, projects/tui-editor/components/editor-socket/styles/text.less, projects/tui-editor/components/toolbar-tools/list-configs/list-configs.component.ts, projects/tui-editor/components/toolbar-tools/list-configs/list-configs.template.html, projects/tui-editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/tui-editor/extensions/starter-kit/starter-kit.ts, projects/tui-editor/package.json, projects/tui-editor/tokens/editor-options.ts
=> feat: add checkbox

projects/demo/src/app/app.pages.ts, projects/demo/src/app/app.routes.ts, projects/demo/src/app/constants/demo-path.ts, projects/demo/src/app/pages/mention/editor-mention.component.html, projects/demo/src/app/pages/mention/editor-mention.component.ts, projects/demo/src/app/pages/mention/editor-mention.module.ts, projects/demo/src/app/pages/mention/examples/1/index.html, projects/demo/src/app/pages/mention/examples/1/index.less, projects/demo/src/app/pages/mention/examples/1/index.ts, projects/tui-editor/components/editor/editor.component.html, projects/tui-editor/components/editor/editor.component.ts, projects/tui-editor/components/toolbar-tools/font-size/font-size.component.ts, projects/tui-editor/extensions/index.ts, projects/tui-editor/extensions/mention/index.ts, projects/tui-editor/extensions/mention/mention.extension.ts, projects/tui-editor/extensions/mention/ng-package.json, projects/tui-editor/utils/get-selection-state.ts, projects/tui-editor/utils/index.ts
=> feat: add mention extension

projects/tui-editor/components/editor-socket/styles/list.less
=> fix: reset counter list for nested li inside details

projects/tui-editor/package.json
`v1` version of #1093
Not 100% sure about peer dependency version ranges. Let me know if some of those need to be extended.
=> [v1] fix: mark some peer dependencies as optional and remove some unnecessary peer dependencies

projects/editor/src/components/edit-link/utils/edit-link-parse-url.ts, projects/editor/test/edit-link-parse.spec.ts
Closes https://github.com/taiga-family/editor/issues/1109
=> fix: invalid url

projects/editor/src/components/editor/editor.component.ts
=> fix: drop redundant dependency

projects/tui-editor/components/editor-socket/editor-socket.component.less, projects/tui-editor/components/editor/editor.component.less
=> fix: add clearfix

projects/editor/src/components/toolbar-tools/code/code.component.ts, projects/editor/src/components/toolbar-tools/details/details-remove/details-remove.component.ts, projects/editor/src/components/toolbar-tools/group/group.component.ts
=> chore: refactor toolbar tools

projects/editor/src/components/editor/editor.component.less
Close https://github.com/taiga-family/editor/issues/1326
=> fix : editor outline-color

projects/editor/components/editor/editor.component.ts
=> chore: editor autofocus fix #2

projects/editor/extensions/indent-outdent/index.ts
=> chore: tab extension fix #2

projects/editor/components/editor-socket/editor-socket.component.less
=> fix: fix inserting hard break with Shift+Enter shortcut after paragraph

projects/editor/components/edit-link/utils/edit-link-parse-url.ts, projects/editor/test/edit-link-parse.spec.ts
=> fix: support nested urls inside query params

projects/editor/extensions/link/index.ts
=> fix: performance tiptap link issue

projects/demo/src/app/pages/embed/html5/examples/1/index.ts
Fixes https://github.com/taiga-family/editor/issues/1631
=> chore(demo): update documentation

projects/demo/src/app/pages/toolbar/bottom/examples/1/index.less, projects/demo/src/app/pages/toolbar/floating/examples/1/index.html, projects/demo/src/app/pages/toolbar/floating/examples/1/index.less, projects/demo/src/app/pages/toolbar/floating/examples/1/index.ts, projects/demo/src/app/pages/toolbar/floating/index.less, projects/demo/src/app/pages/toolbar/floating/index.ts, projects/demo/src/styles.less, projects/editor/components/editor/editor.component.html, projects/editor/components/editor/editor.component.ts, projects/editor/components/toolbar/toolbar.style.less
https://github.com/user-attachments/assets/d822e356-d9fa-473c-8f83-5a105a8ec614
=> feat: improve floating toolbar

projects/demo/src/styles.less
=> chore(demo): small fix

projects/editor/components/toolbar-tools/table-row-column-manager/index.html, projects/editor/components/toolbar/toolbar.style.less
Fixes https://github.com/taiga-family/taiga-ui/issues/8479
=> fix: focus removed from editor when clicking disabled buttons in toolbar

projects/editor/common/editor-adapter.ts, projects/editor/components/editor/editor.component.ts, projects/editor/directives/tiptap-editor/tiptap-editor.directive.ts
=> fix: reuse value state after first transformation

projects/editor/extensions/group/index.ts
=> fix: applying a mismatched transaction in group extension

projects/demo-playwright/tests/img.spec.ts, projects/editor/components/editor/editor.component.ts
=> fix: listen resize events after any DOM changes

projects/editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/editor/extensions/jump-anchor/index.ts, projects/editor/extensions/link/index.ts, projects/editor/utils/get-selected-content.ts, projects/editor/utils/get-sliced-fragment.ts
=> fix: cannot read properties of undefined `reading nodeSize`

projects/demo-playwright/tests/toolbar.spec.ts, projects/demo/src/app/pages/starter/index.html, projects/demo/src/app/pages/starter/index.ts, projects/editor/components/editor/editor.component.ts
=> fix: do not blur any focused inputs

projects/editor/components/toolbar-tools/align-content/index.html, projects/editor/components/toolbar-tools/align-content/index.ts, projects/editor/components/toolbar-tools/code/index.html, projects/editor/components/toolbar-tools/code/index.ts, projects/editor/components/toolbar-tools/details/details-remove/index.html, projects/editor/components/toolbar-tools/details/details-remove/index.ts, projects/editor/components/toolbar-tools/details/index.html, projects/editor/components/toolbar-tools/details/index.ts, projects/editor/components/toolbar-tools/font-size/index.html, projects/editor/components/toolbar-tools/font-size/index.ts, projects/editor/components/toolbar-tools/font-style/index.html, projects/editor/components/toolbar-tools/font-style/index.ts, projects/editor/components/toolbar-tools/group/index.html, projects/editor/components/toolbar-tools/group/index.ts, projects/editor/components/toolbar-tools/highlight-color/index.html, projects/editor/components/toolbar-tools/highlight-color/index.ts, projects/editor/components/toolbar-tools/list-configs/index.html, projects/editor/components/toolbar-tools/list-configs/index.ts, projects/editor/components/toolbar-tools/table-cell-color/index.html, projects/editor/components/toolbar-tools/table-cell-color/index.ts, projects/editor/components/toolbar-tools/table-create/index.html, projects/editor/components/toolbar-tools/table-create/index.ts, projects/editor/components/toolbar-tools/table-merge-cells/index.html, projects/editor/components/toolbar-tools/table-merge-cells/index.ts, projects/editor/components/toolbar-tools/table-row-column-manager/index.html, projects/editor/components/toolbar-tools/table-row-column-manager/index.ts, projects/editor/components/toolbar-tools/text-color/index.html, projects/editor/components/toolbar-tools/text-color/index.ts, projects/editor/components/toolbar/toolbar.component.ts, projects/editor/components/toolbar/toolbar.template.html
=> fix: change default position for hints

projects/demo/src/app/pages/toolbar/custom/examples/1/custom-toolbar/index.less, projects/editor/components/editor/editor.component.less, projects/editor/components/toolbar/toolbar.style.less
=> fix: wrong css imports

projects/editor/common/editor-adapter.ts, projects/editor/components/editor/editor.component.ts, projects/editor/directives/tiptap-editor/tiptap-editor.service.ts
=> feat: support history management by automatically from form control

projects/editor/components/editor/editor.component.html
=> fix: wrong placeholder position

projects/editor/components/edit-link/edit-link.component.ts, projects/editor/components/edit-link/edit-link.style.less, projects/editor/components/edit-link/edit-link.template.html, projects/editor/components/editor/dropdown/dropdown-toolbar.directive.ts, projects/editor/components/editor/editor.component.ts, projects/editor/extensions/link/index.ts, projects/editor/utils/get-sliced-fragment.ts
=> fix: wrong behaviour in Safari for tui-edit-link

projects/editor/extensions/table/index.ts
=> feat: enable last column resizable

projects/demo/src/app/pages/custom-tool/color-picker/examples/1/custom-color-picker/index.ts, projects/editor/components/toolbar-tools/highlight-color/index.ts, projects/editor/components/toolbar-tools/table-cell-color/index.ts, projects/editor/styles/editor-toolbar.css
Fixes #1749
add tuiPlaceHost with styles `position: relative`
=> fix: colored horizontal bar place

projects/editor/components/editor-socket/editor-socket.component.ts, projects/editor/extensions/link/index.ts
=> fix: second click on an anchor link should scroll to the target

package-lock.json, projects/demo/src/app/app.pages.ts, projects/demo/src/app/app.routes.ts, projects/demo/src/app/pages/character-counter/examples/1/index.html, projects/demo/src/app/pages/character-counter/examples/1/index.less, projects/demo/src/app/pages/character-counter/examples/1/index.ts, projects/demo/src/app/pages/character-counter/index.html, projects/demo/src/app/pages/character-counter/index.ts, projects/demo/src/app/shared/routes.ts, projects/editor/package.json
Fixes https://github.com/taiga-family/editor/issues/1693
=> feat: add character counter example

projects/editor/common/editor-options.ts, projects/editor/common/editor-sanitizer.ts
Fixes https://github.com/taiga-family/taiga-ui/issues/10688
=> chore(editor): migrate to `InjectionToken` instead `tuiCreateToken` utility

projects/demo-playwright/tests/links.spec.ts, projects/demo-playwright/tests/slash.spec.ts, projects/editor/extensions/link/index.ts
=> fix: cannot read properties of undefined when reading nodeSize

projects/editor/components/editor-resizable/editor-resizable.abstract.ts, projects/editor/components/editor/editor.component.html
Fixes https://github.com/taiga-family/taiga-ui/issues/10936
=> feat: increase performance

.github/screenshot-bot.config.yml
Relates:
- https://github.com/taiga-family/argus/issues/276
=> ci: use modern config API for screenshot report action

projects/demo/src/app/pages/details/examples/1/index.ts, projects/editor/components/editor-socket/styles/details.less
=> fix: wrong details width

projects/demo-playwright/tests/groups.spec.ts, projects/demo-playwright/tests/slash.spec.ts
=> chore: flaky

projects/demo-playwright/tests/details.spec.ts, projects/demo/src/app/pages/details/examples/2/index.html, projects/demo/src/app/pages/details/examples/2/index.ts, projects/demo/src/app/pages/details/index.html, projects/demo/src/app/pages/details/index.ts, projects/editor/extensions/details/index.ts
Fixes https://github.com/taiga-family/editor/issues/1840
=> feat: introduce `defaultOpen` and `inheritOpen` for details component

projects/demo/src/app/pages/focus/examples/1/index.less, projects/demo/src/app/pages/images/resizable/examples/1/index.ts, projects/editor/common/editor-adapter.ts, projects/editor/common/image.ts, projects/editor/common/index.ts, projects/editor/common/pm-css-classes.ts, projects/editor/common/types/index.ts, projects/editor/components/edit-link/edit-link.component.ts, projects/editor/components/editor-socket/styles/media.less, projects/editor/components/editor/dropdown/dropdown-toolbar.directive.ts, projects/editor/components/editor/editor.component.html, projects/editor/components/editor/editor.component.ts, projects/editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/editor/extensions/image-editor/image-editor.extension.ts, projects/editor/extensions/image-editor/image-editor.html, projects/editor/extensions/image-editor/image-editor.less, projects/editor/extensions/image-editor/image-editor.ts, projects/editor/extensions/link/index.ts, projects/editor/extensions/tiptap-node-view/index.ts, projects/editor/tools/buttons/anchor.ts, projects/editor/tools/buttons/link.ts
=> feat: allow selecting images with the keyboard
